### ISSUE TITLE
Add more profiling

### ISSUE THREAD

**Issue by FranklinChen** [stackbuilders/reverse#1]
It might be instructive to add use of Criterion and Profiteur to follow up with a blog post on profiling.

**Comment by jpvillaisaza** [comment]
@FranklinChen Thank you very much, it sounds like a great idea. I'll start working on it.

**Comment by jpvillaisaza** [comment]
Profiteur is still on the list, but criterion was included in http://www.stackbuilders.com/news/obverse-versus-reverse-benchmarking-in-haskell-with-criterion.
